benches/benches.rs
src/lib.rs
src/tests.rs
tests/integration_tests.rs

Calculating column is slow, especially for utf8 columns.
This PR removes column computation every slice and rather offers two methods instead for this: `LocatedSpan::get_column()` and `LocatedSpan::get_column_utf8()`.
That's a good compromise:
- users who don't care about that won't be impacted by performance degradation (fixes #3)
- users who are sure to have ASCII text (whether they previously checked using `str::is_ascii` or because they assume it) would call `get_column()`
- users who expect UTF8 chars in their program would rather call `get_column_utf8()`

Don't calculate column every time, rather offer methods for that

---

Cargo.toml

Major version bump because of BurntSushi/rust-memchr#18
memchr::memchr's interface did not change,
so allow using either version for better unification chances

Bump memchr version

---

Cargo.toml
benches/benches.rs
src/lib.rs
src/tests.rs
tests/integration_tests.rs

Compiles against [Geal/nom#a53febdfdf99d16c0177f5c605bd98481a4ec50f](https://github.com/Geal/nom/tree/a53febdfdf99d16c0177f5c605bd98481a4ec50f)
I was playing around with a small parser and tried out the latest changes with upstream nom. These are the changes that I had to patch into this library to get it compiling.
Very, very minimally tested (as in, it compiles and I have a micro-sized nom parser using it), and nom might change again before the proper 4.0 release, but I thought I'd share the work I did to get this to compile today.

Inital port to nom 4.0

---

benches/benches.rs
src/lib.rs

It's good in benchmarks (approx 6ns/iter -> less than 4ns/iter), and very good in my Python parser.

Speed up slices '0..' and '..'.

---

.travis.yml
src/lib.rs

Now `alloc` is stabilized. So the feature gate can be removed.
I added CI tests for stable/beta with `alloc`.

Remove alloc feature gate

---

src/lib.rs

I added `AsBytes` for `LocatedSpanEx`.
In [this document](https://github.com/Geal/nom/blob/master/doc/custom_input_types.md), `AsBytes` must be implemented for custom input type.

Impl AsBytes

---

src/lib.rs

* Replace explicit `ToString` implementation for `LocatedSpanEx` with `Display`.
This should make `nom_locate` more ergonomic to use with [Criterion](https://github.com/bheisler/criterion.rs). Note that the type annotation `T` is constrained here by `ToString` instead of `Display` so we can support `Display` for `LocatedSpanEx` even for types that do not implement `Display`, but do implement `ToString`.
Fixes #39.

Implement Display for LocatedSpanEx

---

.travis.yml
Cargo.toml
src/lib.rs
tests/integration_tests.rs

This change gives users the option of using nom_locate without needing to use the default features of nom, e.g. "lexical".

Update nom dependency in Cargo.toml

---

examples/position.rs
src/lib.rs
tests/integration_tests.rs

Mutating `offset` and `fragment` (or building a LocatedSpan from scratch) may result
in undefined behavior if the offset is invalid.
`line` doesn't need to be private, but I'm making it anyway, just in case we ever need it.
Fixes #45 
@0xd34d10cc How does that look?

Make offset/line/fragment private attributes.

---

CHANGELOG.md
src/lib.rs
src/tests.rs

Thanks for the help with my previous pull request! I have decided to create another one for something small that has been bugging me for a bit...
When [the addition of extra information to `LocatedSpan`](https://github.com/fflorent/nom_locate/pull/28) was implemented, a new `LocatedSpanEx` struct was added which includes an `extra` property with generic parameter `X`. Consequently, the original `LocatedSpan` has become a type alias where `X` is set to the empty type `()`.
```rust
pub type LocatedSpan<T> = LocatedSpanEx<T, ()>;
```
However, this is unnecessary as for some time [default type parameters have been allowed](https://github.com/rust-lang/rfcs/blob/master/text/0213-defaulted-type-params.md) — see [the relevant page in the Rust …

Use default type parameter for LocatedSpan

---

src/lib.rs
src/tests.rs

Fixes #54 by providing `impl<T: AsBytes, X: Default> From<T> for LocatedSpan<T, X>`

Implement From<T> for LocatedSpan

---

src/lib.rs
src/tests.rs

There are three main changes in this PR:
Tests were added for dereferencing and hex dumps to prove that there was not a regression in removing the `nom::HexDisplay` implementation.
I suspect the `nom::ExtendInto` and `nom::Slice` implementations could still be generalized in the future, but I haven't been able to find the right combination of type constraints for those just yet.

Improve generalization

---

Cargo.toml
src/lib.rs

I can't implement this marker trait in my own code due to the orphan rule, and it's a [very broadly used](https://crates.io/crates/stable_deref_trait) marker trait and should be safe to implement here. The added dependency doesn't have any transitive dependencies and only contains the trait definitions + simple marker impls.

impl StableDeref for LocatedSpan

---

src/lib.rs
src/tests.rs

Add a function to get the full input line containing the (start point of the) LocatedSpan.
As suggested in #53.

Implement LocatedSpan::get_line().

---

src/lib.rs

The examples that were used in the documentation were still using nom macros from nom 4 (`tag!`, `take_until!`, etc) instead of their function counterparts. I updated the documentation to reflect today's usage of nom. However, the example in "Extra Information" does not compile, and I'm not sure what to do with it.
Finally, there was a typo in the backticks used for one of the example, which didn't render properly in the docs.

Fix documentation examples

---

src/lib.rs
src/tests.rs
tests/integration_tests.rs

Fixes `find_substring` with a byte slice on a byte slice backed `LocatedSpan`.

Generalize FindSubstring impl

---

src/lib.rs

I ended up using this with the arcstr crate, and I needed to genericize the rest of the trait impls, so I'm trying to contribute back upstream!
Let me know what fixes I need to make to documentation and attributes.

Genericizes the rest of the nom traits.

---

src/lib.rs

There are 2 commits on this PR:
* f27b87f7d6090d1d5f688e5ba732eee9778c1b9a Remove bounds on some methods:
Removes the `T: AsBytes` for the methods `new`, `new_extra`, `new_from_raw_offset`, `location_offset`, `location_line` and `fragment`.
* 560c8f6246f9279a35a87446af0b28c9cd43a3e7 Add map method:
Adds the method `map` to `LocatedSpan<T,X>`, which is like the `map` in iterators, but applied to the fragment. (Removed)
* a95a58b Move the map method to use the `extra` field, as it is more useful, as there's no way to update the extra field without using unsafe or forgeting span location

Remove unneeded bounds & add map method

---

src/lib.rs
src/tests.rs

Implement `AsRef<T>` for `LocatedSpan<T, X>` and `AsRef<[u8]>` for `LocatedSpan<T: AsRef<[u8]>, X>`. This makes it usable directly, e.g. in contexts expecting an `AsRef<Path>` or `AsRef<[u8]>`.

Implement AsRef for LocatedSpan

---

src/lib.rs

Closes #62.
I've just found myself needing this feature since I want to parse into a borrowed struct without cloning the original data, and I do not want to return a `LocatedSpan<&'a str>`.

Add methods to take ownership of fragment and extra data

---

.github/workflows/ci.yml
Cargo.toml

Trying to compile on v1.48.0 now fails with:
```
Error: failed to parse manifest at `/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/memchr-2.6.4/Cargo.toml`
Caused by:
failed to parse the `edition` key
```

Bump minimum supported Rust version to 1.63.0
